version: '3.8'

# ============================================================
#  AZHOME SaaS Dev Lab - Docker Compose (WINDOWS DEVELOPMENT)
# ============================================================

services:
  odoo_dev_lab:
    image: odoo:19
    container_name: odoo_dev_lab
    user: root
    environment:
      - HOST=host.docker.internal
      - USER=openpg
      - PASSWORD=openpgpwd
      - AZHOME_PLAN_CODE=saas_gold
      - AZHOME_MAX_USERS=100
      - AZHOME_HOST_OS=windows
    volumes:
      # 1. Addons
      - ./../../az_addons_cons:/mnt/extra-addons
      - ./../../az_addons_saas:/mnt/master-addons
      # 2. Filestore (Dữ liệu folder)
      - ./../../dev_data:/var/lib/odoo
      # 3. Docker Socket
      - //var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8079:8069"
    command: >
      odoo
      --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/master-addons
      --db_host=host.docker.internal
      --db_user=openpg
      --db_password=openpgpwd
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - az_saas_network
    restart: unless-stopped

networks:
  az_saas_network:
    external: true
